name: Tag on Release PR

on:
  pull_request:
    branches:
      - 'releases/**'
      - 'release/**'
  push:
    branches: 
      "**"
    tags: 
      - "**"

jobs:
  validate-tag-in-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Esto es importante para obtener todo el historial

      - name: Check for tag in PR commits
        id: check_tag
        run: |
          # Obtener la lista de commits en el PR
          PR_COMMITS=$(git log --format=%H origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
          
          # Inicializar una variable para rastrear si se encontró un tag
          TAG_FOUND=false
          
          # Iterar sobre cada commit en el PR
          for COMMIT in $PR_COMMITS
          do
            # Verificar si este commit tiene un tag
            TAG=$(git tag --contains $COMMIT)
            if [ ! -z "$TAG" ]; then
              echo "Tag encontrado: $TAG en el commit $COMMIT"
              TAG_FOUND=true
              break
            fi
          done
          
          # Verificar si se encontró algún tag
          if [ "$TAG_FOUND" = false ]; then
            echo "No se encontró ningún tag en los commits del PR"
            exit 1
          else
            echo "Se encontró al menos un tag en los commits del PR"
          fi
      