name: Tag on Release PR

on:
    pull_request:
        branches:
            - 'release/**'
        types: [opened, synchronize, reopened]
    push:
        tags:
            - '**'

jobs:
    print-token:
      permissions: write-all
      name: print-token
      environment: dev
      # needs: pre-pkr
      runs-on: ubuntu-latest

      steps:
          - name: Check out code
            uses: actions/checkout@v2

          - name: Get registration token
            id: getRegToken
            run: |
                curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token

    validate-tag-in-pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # This is important to get all history for the tag check

            - name: Check for tag in PR commits
              id: check_tag
              run: |
                  # Get PR list
                  PR_COMMITS=$(git log --format=%H origin/${{ github.base_ref }}..origin/${{ github.head_ref }})

                  TAG_FOUND=false

                  for COMMIT in $PR_COMMITS
                  do
                    # Verify tag in commit
                    TAG=$(git tag --contains $COMMIT)
                    if [ ! -z "$TAG" ]; then
                      echo "Tag finded: $TAG in commit $COMMIT"
                      TAG_FOUND=true
                      break
                    fi
                  done

                  if [ "$TAG_FOUND" = false ]; then
                    echo "Not found tag in this project"
                    exit 1
                  else
                    echo "Tags is provided"
                  fi
            - name: Add comment
              run: gh pr comment "$PRNUMBER" --body "$BODY"
              if: failure()
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_REPO: ${{ github.repository }}
                  PRNUMBER: ${{ github.event.pull_request.number }}
                  BODY: >
                      No se encontró ningún tag en los commits de este PR. Por favor, asegúrate de agregar un tag antes de fusionar.
